name: Deploy GCP

on:
  push:
    branches: [ main ]

env:
  FLASK_APP: ${{ secrets.FLASK_APP }}
  FLASK_ENV: ${{ secrets.FLASK_ENV }}
  FLASK_DEBUG: ${{ secrets.FLASK_DEBUG }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  MONGO_URI: ${{ secrets.MONGO_URI }}
  GOOGLE_CLIENT_SECRETS: ${{ secrets.GOOGLE_CLIENT_SECRETS }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  OAUTHLIB_INSECURE_TRANSPORT: ${{ secrets.OAUTHLIB_INSECURE_TRANSPORT }}
  FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  RUN_REGION: southamerica-east1
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:

  deploy:

    name: "Config GCP"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/conectacontactbackend:latest
  
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: GCP Auth
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Docker Build Image
        run: docker build -t $IMAGE_NAME .
      
      - name: Push Docker Image
        run: docker push $IMAGE_NAME
      
      - name : Deploy Docker Image
        run: gcloud run deploy conectacontact --image $IMAGE_NAME --region $RUN_REGION --set-env-vars FLASK_APP=app.py,FLASK_ENV=development,SECRET_KEY=algumseguredo,FRONTEND_URL=http://localhost:8080,OAUTHLIB_INSECURE_TRANSPORT=1
