apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: conectacontactbackend
  namespace: '626571889159'
  selfLink: >-
    /apis/serving.knative.dev/v1/namespaces/626571889159/services/conectacontactbackend
  uid: f7131446-a414-4375-a6d5-3ca068327e17
  resourceVersion: AAXuXYhFSDE
  generation: 2
  creationTimestamp: '2022-11-26T10:53:34.548826Z'
  labels:
    cloud.googleapis.com/location: southamerica-east1
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: vinicius_stormoski@estudante.sesisenai.org.br
    serving.knative.dev/lastModifier: vinicius_stormoski@estudante.sesisenai.org.br
    client.knative.dev/user-image: >-
      gcr.io/conectacontact/conectacontactbackend@sha256:448de02c49570b5614389f291b45efdc6563d9d29e0c76bc24fe5b137116fa42
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      name: conectacontact-00002-qoh
      annotations:
        run.googleapis.com/client-name: cloud-console
        autoscaling.knative.dev/maxScale: '100'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 626571889159-compute@developer.gserviceaccount.com
      containers:
      - image: >-
          gcr.io/conectacontact/conectacontactbackend@sha256:448de02c49570b5614389f291b45efdc6563d9d29e0c76bc24fe5b137116fa42
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: FLASK_APP
          value: app.py
        - name: FLASK_ENV
          value: development
        - name: SECRET_KEY
          value: algumseguredo
        - name: FRONTEND_URL
          value: 'http://localhost:8080'
        - name: OAUTHLIB_INSECURE_TRANSPORT
          value: '1'
        - name: GOOGLE_CLIENT_SECRETS
          valueFrom:
            secretKeyRef:
              key: '1'
              name: GOOGLE_CLIENT_SECRETS
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: '1'
              name: GOOGLE_CLIENT_ID
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              key: '1'
              name: MONGO_URI
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 3
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2022-11-26T10:59:29.065651Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2022-11-26T10:59:23.046604Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2022-11-26T10:59:29.164337Z'
  latestReadyRevisionName: conectacontactbackend-00002-qoh
  latestCreatedRevisionName: conectacontactbackend-00002-qoh
  traffic:
  - revisionName: conectacontactbackend-00002-qoh
    percent: 100
    latestRevision: true
  url: https://conectacontact-myb7gebzdq-rj.a.run.app
  address:
    url: https://conectacontact-myb7gebzdq-rj.a.run.app
